USE master
DROP DATABASE IF EXISTS ASM_AClip
CREATE DATABASE ASM_AClip
USE ASM_AClip

GO
CREATE TABLE USERS(
	Username VARCHAR(64) NOT NULL,
	Password VARCHAR(64) NOT NULL,
	Fullname NVARCHAR(256) NOT NULL,
	Email VARCHAR(256) UNIQUE NOT NULL,
	Role BIT NOT NULL, --1 is admin, 0 is user
	PRIMARY KEY(Username)
);

GO
CREATE TABLE VIDEOS(
	IDYoutube VARCHAR(11) NOT NULL,
	Title NVARCHAR(512) NOT NULL, 
	Description NVARCHAR(2048),
	Thumbnail VARCHAR(256) NOT NULL,
	Time DATETIME NOT NULL,
	PRIMARY KEY(IDYoutube)
);

GO
CREATE TABLE USERSVIEWED(
	ID BIGINT IDENTITY(1,1) NOT NULL,
	IDUser VARCHAR(64) NOT NULL,
	IDVideo VARCHAR(11) NOT NULL,
	PRIMARY KEY(ID),
	FOREIGN KEY (IDUser) REFERENCES USERS(Username),
	FOREIGN KEY (IDVideo) REFERENCES VIDEOS(IDYoutube)
);

GO
CREATE TABLE USERSLIKED(
	ID BIGINT IDENTITY(1,1) NOT NULL,
	IDUser VARCHAR(64) NOT NULL,
	IDVideo VARCHAR(11) NOT NULL,
	Time DATETIME NOT NULL,
	PRIMARY KEY(ID),
	FOREIGN KEY (IDUser) REFERENCES USERS(Username),
	FOREIGN KEY (IDVideo) REFERENCES VIDEOS(IDYoutube)
);

DROP PROC IF EXISTS sp_ReportOfYear
GO
CREATE PROC sp_ReportOfYear(@year INT) AS
BEGIN
    select L.IDVideo, COUNT(*) as 'likes', MAX(L.Time) AS 'newestLiked', MIN(L.Time) AS 'oldestLiked'
	from USERSLIKED as L
	WHERE YEAR(Time) = @year
	GROUP BY IDVideo
END